In [3]:
import pandas as pd
import numpy as np

In [6]:
# zeros 
# it takes one arg (size of array) 
# and creates an array of that size filled with zeros

var = np.zeros(10)
var

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
# ones
# it takes one arg (size of array) 
# and creates an array of that size filled with ones
var = np.ones(10)
var

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
# full
# it takes TWO arg (size of array, to fill with) 
# and creates an array of that size filled with 2nd arg
var = np.full(10, 2.5)
var

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [13]:
# python list => numpy array
var = np.array([1,2,3,4,5])
var

array([1, 2, 3, 4, 5])

In [23]:
# index
array = np.array([9,8,7,6,5,4,3])
array # array([9, 8, 7, 6, 5, 4, 3])
array[1] # np.int64(8)
print(array[1]) # 8
np.arange(3,10) #  creates a range of numbers array([3, 4, 5, 6, 7, 8, 9])

8


array([3, 4, 5, 6, 7, 8, 9])