In [2]:
pip list

Package                   Version
------------------------- -----------
anyio                     4.15.1
argon2-cffi               25.1.0
argon2-cffi-bindings      26.1.0
arrow                     1.4.0
asttokens                 3.0.2
async-lru                 2.3.0
attrs                     26.1.0
babel                     2.18.0
beautifulsoup4            4.15.0
bleach                    6.4.0
certifi                   2026.7.22
cffi                      2.1.1
charset-normalizer        3.5.1
cloudpickle               3.1.2
colorama                  0.4.6
comm                      0.2.3
contourpy                 1.4.0
cycler                    0.12.1
debugpy                   1.8.21
defusedxml                0.7.1
executing                 2.2.1
fastjsonschema            2.22.2
fonttools                 4.66.0
fqdn                      1.5.1
gitdb                     4.0.12
GitPython                 3.1.62
h11                       0.16.0
httpcore                  1.0.9
httpx          

In [3]:
import pandas as pd
import numpy as np

In [6]:
# zeros 
# it takes one arg (size of array) 
# and creates an array of that size filled with zeros

var = np.zeros(10)
var

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
# ones
# it takes one arg (size of array) 
# and creates an array of that size filled with ones
var = np.ones(10)
var

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
# full
# it takes TWO arg (size of array, to fill with) 
# and creates an array of that size filled with 2nd arg
var = np.full(10, 2.5)
var

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [13]:
# python list => numpy array
var = np.array([1,2,3,4,5])
var

array([1, 2, 3, 4, 5])

In [23]:
# index
array = np.array([9,8,7,6,5,4,3])
array # array([9, 8, 7, 6, 5, 4, 3])
array[1] # np.int64(8)
print(array[1]) # 8
np.arange(3,10) #  creates a range of numbers array([3, 4, 5, 6, 7, 8, 9])

8


array([3, 4, 5, 6, 7, 8, 9])

In [1]:
pip list

Package                   Version
------------------------- -----------
anyio                     4.15.1
argon2-cffi               25.1.0
argon2-cffi-bindings      26.1.0
arrow                     1.4.0
asttokens                 3.0.2
async-lru                 2.3.0
attrs                     26.1.0
babel                     2.18.0
beautifulsoup4            4.15.0
bleach                    6.4.0
certifi                   2026.7.22
cffi                      2.1.1
charset-normalizer        3.5.1
cloudpickle               3.1.2
colorama                  0.4.6
comm                      0.2.3
contourpy                 1.4.0
cycler                    0.12.1
debugpy                   1.8.21
defusedxml                0.7.1
executing                 2.2.1
fastjsonschema            2.22.2
fonttools                 4.66.0
fqdn                      1.5.1
gitdb                     4.0.12
GitPython                 3.1.62
h11                       0.16.0
httpcore                  1.0.9
httpx          